apiVersion: v1
kind: Service
metadata:
  name: {{ include "asteroid-game.fullname" . }}
  labels: {{ include "asteroid-game.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ include "asteroid-game.selectorLabels" . | nindent 4 }}
